# Generated by Django 5.0.6 on 2024-07-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='author',
        ),
    ]
